function check_fdate_formatting(fdatepick, patent_number)   
    
if ~(numel(fdatepick)==6)
    fprintf('Filing date format (%s) [patent: %s] should be 6 characters long.\n', ...
        fdatepick, patent_number{ix_patent})
elseif ~(isempty(strfind(fdatepick, ' ')))
    fprintf('Filing dates (%s) [patent: %s] should not contain space.\n', ...
        fdatepick, patent_number{ix_patent})
elseif isempty(intersect((1790:2015), str2double(fdatepick(1:4)))) || ...
        isempty(intersect((1:12), str2double(fdatepick(5:6))))
    fprintf('Filing date format (%s) [patent: %s] does not look like a proper date (or filing date is implausibly early).\n', ...
        fdatepick, patent_number{ix_patent})
end
