function check_fdate_formatting(fdatepick, patnrpick)   
    
if ~(numel(fdatepick)==6)
    fprintf('\tFiling date format (%s) [patent: %s] should be 6 characters long.\n', ...
        fdatepick, patnrpick)
elseif ~(isempty(strfind(fdatepick, ' ')))
    fprintf('\tFiling dates (%s) [patent: %s] should not contain space.\n', ...
        fdatepick, patnrpick)
elseif isempty(intersect((1790:2015), str2double(fdatepick(1:4)))) || ...
        isempty(intersect((1:12), str2double(fdatepick(5:6))))
    fprintf('\tFiling date format (%s) [patent: %s] does not look like a proper date (or filing date is implausibly early).\n', ...
        fdatepick, patnrpick)
end
