function keyword_collection = define_keywords

keyword_collection = {'automatization'; 'automate'; 'autom'; 'reshoring'; ...
    'outsourcing'; 'mechani'; 'automization'; 'offshoring'; 'automatic'; ...
    'automated'};